# TODO index

Regenerated: {{ISO-8601 timestamp}}

This index is auto-regenerated by `update-todos review` and appended-to by `update-todos capture | clarify | resolve`. Do not edit by hand — changes will be overwritten.

See `README.md` in this folder for conventions and the boundary with `developer-diary`.

## Summary

- **Open:** {{N}} (active) + {{N}} (blocked) + {{N}} (deferred) = {{N}} total
- **Inbox:** {{N}} unclarified
- **Archive:** {{N}} resolved, {{N}} wont-fix, {{N}} discarded
- **Expiring within 7 days:** {{N}}
- **Stale (>30d without update):** {{N}}
- **Orphans (no related links):** {{N}}
- **Dead-blockers (blocker resolved, not yet moved to active):** {{N}}

## Active

| ID | Next-step | Priority | Scope | Expires | Very-next-action |
|---|---|---|---|---|---|

## Blocked

| ID | Blocked by | Next-step | Expires |
|---|---|---|---|

## Inbox (unclarified)

| ID | Created | Next-step (guess) | Discovery summary |
|---|---|---|---|

## Deferred (someday/maybe)

| ID | Expires | Tags |
|---|---|---|

## Archive (most-recent 20)

| ID | Resolution type | Resolved on | Resolved in |
|---|---|---|---|

## Warnings

{{One line per warning — orphans, dead-blockers, bidirectional link violations, invalid next-step values, stale items.}}
