#!/usr/bin/env bash
# configure.sh — lazy, first-use configuration for this skill.
#
# Called by the agent on first invocation when ~/.config/<skill>/config.yaml
# is missing. Safe to re-run: --repair updates an existing file.
#
# Portability rules:
#   - POSIX bash only. No Python, no Node, no jq, no yq.
#   - Write config to XDG path. Chmod 0600.
#   - Never modify files outside ~/.config/<skill>/.

set -euo pipefail

# Derive skill name from the parent directory of this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_NAME="$(basename "$(dirname "$SCRIPT_DIR")")"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/${SKILL_NAME}"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"

MODE="init"
if [[ "${1:-}" == "--repair" ]]; then
  MODE="repair"
fi

prompt() {
  # $1 = key, $2 = description, $3 = default (optional)
  local key="$1" desc="$2" default="${3:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "${desc} [${default}]: " value
    value="${value:-$default}"
  else
    read -r -p "${desc}: " value
  fi
  printf '%s: %s\n' "$key" "$value"
}

main() {
  if [[ "$MODE" == "init" && -f "$CONFIG_FILE" ]]; then
    echo "Config already exists at $CONFIG_FILE"
    echo "Run with --repair to update it."
    exit 0
  fi

  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"

  echo "Configuring ${SKILL_NAME}."
  echo "Values will be written to ${CONFIG_FILE} (permissions 0600)."
  echo

  # ---- EDIT THIS BLOCK for your skill's required keys ----
  {
    echo "# ${SKILL_NAME} configuration"
    echo "# Generated by scripts/configure.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    prompt "api_endpoint" "API endpoint URL" "https://api.example.com"
    prompt "project_id" "Project ID"
  } > "$CONFIG_FILE.tmp"
  # ---- END edit block ----

  mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"

  echo
  echo "Wrote ${CONFIG_FILE}."
  echo "Review it with: cat ${CONFIG_FILE}"
}

main "$@"
